## Defining the matrix

In [ ]:
import numpy as np
data = np.array([[2.5, 2.4, 2.3], [0.5, 0.7, 0.9], [2.2, 2.9, 2.7]])
data

array([[2.5, 2.4, 2.3],
       [0.5, 0.7, 0.9],
       [2.2, 2.9, 2.7]])

## Extracting eigenvalue and vector

In [ ]:
values, vectors = np.linalg.eig(data)
print("eigenvector :", vectors)
print("eigenvalues :", values)

eigenvector : [[ 0.67680159  0.85325227  0.06974548]
 [ 0.19870841 -0.35133343 -0.72981306]
 [ 0.7088403  -0.38538992  0.68007975]]
eigenvalues : [ 5.61351647  0.4729359  -0.18645237]


In [ ]:
import tensorflow as tf
values, vectors = tf.linalg.eigh(data)
print("eigenvector :", vectors)
print("eigenvalues :", values)

eigenvector : tf.Tensor(
[[ 0.24654269 -0.81910062  0.51796802]
 [ 0.73950474  0.50444354  0.44572351]
 [-0.62637803  0.27314994  0.73009566]], shape=(3, 3), dtype=float64)
eigenvalues : tf.Tensor([-1.58967421  1.45842879  6.03124543], shape=(3,), dtype=float64)


## Fitting the PCA on matrix

In [ ]:
from sklearn.decomposition import PCA
import numpy as np
print(data)
pca = PCA()
pca.fit(data)

[[2.5 2.4 2.3]
 [0.5 0.7 0.9]
 [2.2 2.9 2.7]]


PCA()

## Extracting eigenvectors and values

In [ ]:
print("eigenvectors :", pca.components_)
print("eigenvalues :", pca.explained_variance_)

eigenvectors : [[-0.57806669 -0.63095309 -0.51743318]
 [ 0.81592449 -0.45495264 -0.35677069]
 [ 0.01030203  0.62842365 -0.77780305]]
eigenvalues : [3.29123908e+00 9.54275859e-02 3.18326380e-33]
